using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LogoDetectionFANET45
{
    public static class db
    {
        public static List<String> images =
            new List<String> {
                "LogoDetectionFANET45.Resources.91.jpg",
                "LogoDetectionFANET45.Resources.92.jpg",
                "LogoDetectionFANET45.Resources.93.jpg",
                "LogoDetectionFANET45.Resources.94.jpg",
                "LogoDetectionFANET45.Resources.95.jpg",
                "LogoDetectionFANET45.Resources.96.jpg",
                "LogoDetectionFANET45.Resources.97.jpg",
                "LogoDetectionFANET45.Resources.98.jpg",
                "LogoDetectionFANET45.Resources.99.jpg",
                "LogoDetectionFANET45.Resources.100.jpg"
            };
        public static List<String> labels =
            new List<String> {
                "starbucks",
                "starbucks",
                "starbucks",
                "starbucks",
                "starbucks",
                "starbucks",
                "starbucks",
                "starbucks",
                "starbucks",
                "starbucks"
            };
        public static List<DateTime> dates =
            new List<DateTime>
            {
                new DateTime(2014,11,25),
                new DateTime(2014,11,25),
                new DateTime(2014,11,24),
                new DateTime(2014,11,24),
                new DateTime(2014,11,23),
                new DateTime(2014,11,22),
                new DateTime(2014,11,29),
                new DateTime(2014,11,29),
                new DateTime(2014,11,28),
                new DateTime(2014,11,28)
            };
        public static List<String> location =
            new List<String> 
            { 
                "31",
                "31",
                "31",
                "32",
                "32",
                "91",
                "11",
                "62",
                "74",
                "16"
            };
        public static List<String> username =
            new List<String> 
            { 
                "ponta0225",
                "thenewboston",
                "alexanderwangny",
                "beachb0y",
                "aditpk",
                "muhammadiqbal2777",
                "cobolover221",
                "taylorswiftfan123",
                "maskuman28",
                "josgojos44"
            };
        public static List<int> followers =
            new List<int> 
            { 
                551,
                105,
                664,
                14,
                60,
                420,
                551,
                105,
                664,
                14,
                60,
                420
            };
        public static List<KeyValuePair<DateTime, int>> chartStats =
            new List<KeyValuePair<DateTime, int>>
            {
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,25), 2),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,24), 2),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,23), 1),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,22), 1),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,29), 2),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,28), 2)
            };
        public static List<KeyValuePair<DateTime, int>> dummyChartStats =
            new List<KeyValuePair<DateTime, int>>
            {
                new KeyValuePair<DateTime,int>(new DateTime(2014,12,25), 72),
                new KeyValuePair<DateTime,int>(new DateTime(2014,12,24), 22),
                new KeyValuePair<DateTime,int>(new DateTime(2014,12,23), 31),
                new KeyValuePair<DateTime,int>(new DateTime(2014,12,22), 19),
                new KeyValuePair<DateTime,int>(new DateTime(2014,12,21), 22),
                new KeyValuePair<DateTime,int>(new DateTime(2014,12,20), 52),
                new KeyValuePair<DateTime,int>(new DateTime(2014,12,19), 81),
                new KeyValuePair<DateTime,int>(new DateTime(2014,12,18), 95),
                new KeyValuePair<DateTime,int>(new DateTime(2014,12,17), 42),
                new KeyValuePair<DateTime,int>(new DateTime(2014,12,16), 32),
                new KeyValuePair<DateTime,int>(new DateTime(2014,12,15), 21),
                new KeyValuePair<DateTime,int>(new DateTime(2014,12,14), 12),
                new KeyValuePair<DateTime,int>(new DateTime(2014,12,13), 23),
                new KeyValuePair<DateTime,int>(new DateTime(2014,12,12), 22),
                new KeyValuePair<DateTime,int>(new DateTime(2014,12,11), 8),
                new KeyValuePair<DateTime,int>(new DateTime(2014,12,10), 5),
                new KeyValuePair<DateTime,int>(new DateTime(2014,12,9), 30),
                new KeyValuePair<DateTime,int>(new DateTime(2014,12,8), 51),
                new KeyValuePair<DateTime,int>(new DateTime(2014,12,7), 33),
                new KeyValuePair<DateTime,int>(new DateTime(2014,12,6), 66),
                new KeyValuePair<DateTime,int>(new DateTime(2014,12,5), 2),
                new KeyValuePair<DateTime,int>(new DateTime(2014,12,4), 10),
                new KeyValuePair<DateTime,int>(new DateTime(2014,12,3), 9),
                new KeyValuePair<DateTime,int>(new DateTime(2014,12,2), 17),
                new KeyValuePair<DateTime,int>(new DateTime(2014,12,1), 12),
                
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,25), 72),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,24), 22),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,23), 31),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,22), 19),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,21), 22),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,20), 52),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,19), 81),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,18), 95),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,17), 42),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,16), 32),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,15), 21),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,14), 12),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,13), 23),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,12), 22),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,11), 8),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,10), 5),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,9), 30),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,8), 51),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,7), 33),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,6), 66),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,5), 2),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,4), 10),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,3), 9),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,2), 17),
                new KeyValuePair<DateTime,int>(new DateTime(2014,11,1), 12),

                new KeyValuePair<DateTime,int>(new DateTime(2014,10,25), 72),
                new KeyValuePair<DateTime,int>(new DateTime(2014,10,24), 22),
                new KeyValuePair<DateTime,int>(new DateTime(2014,10,23), 31),
                new KeyValuePair<DateTime,int>(new DateTime(2014,10,22), 19),
                new KeyValuePair<DateTime,int>(new DateTime(2014,10,21), 22),
                new KeyValuePair<DateTime,int>(new DateTime(2014,10,20), 52),
                new KeyValuePair<DateTime,int>(new DateTime(2014,10,19), 81),
                new KeyValuePair<DateTime,int>(new DateTime(2014,10,18), 95),
                new KeyValuePair<DateTime,int>(new DateTime(2014,10,17), 42),
                new KeyValuePair<DateTime,int>(new DateTime(2014,10,16), 32),
                new KeyValuePair<DateTime,int>(new DateTime(2014,10,15), 21),
                new KeyValuePair<DateTime,int>(new DateTime(2014,10,14), 12),
                new KeyValuePair<DateTime,int>(new DateTime(2014,10,13), 23),
                new KeyValuePair<DateTime,int>(new DateTime(2014,10,12), 22),
                new KeyValuePair<DateTime,int>(new DateTime(2014,10,11), 8),
                new KeyValuePair<DateTime,int>(new DateTime(2014,10,10), 5),
                new KeyValuePair<DateTime,int>(new DateTime(2014,10,9), 30),
                new KeyValuePair<DateTime,int>(new DateTime(2014,10,8), 51),
                new KeyValuePair<DateTime,int>(new DateTime(2014,10,7), 33),
                new KeyValuePair<DateTime,int>(new DateTime(2014,10,6), 66),
                new KeyValuePair<DateTime,int>(new DateTime(2014,10,5), 2),
                new KeyValuePair<DateTime,int>(new DateTime(2014,10,4), 10),
                new KeyValuePair<DateTime,int>(new DateTime(2014,10,3), 9),
                new KeyValuePair<DateTime,int>(new DateTime(2014,10,2), 17),
                new KeyValuePair<DateTime,int>(new DateTime(2014,10,1), 12)
            };
        public static List<String> images_extended =
            new List<String> {
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/1.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/2.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/3.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/4.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/5.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/6.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/7.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/8.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/9.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/10.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/11.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/12.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/13.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/14.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/15.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/16.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/17.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/18.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/19.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/20.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/21.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/22.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/23.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/24.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/25.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/26.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/27.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/28.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/29.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/30.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/31.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/32.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/33.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/34.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/35.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/36.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/37.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/38.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/39.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/40.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/41.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/42.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/43.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/44.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/45.jpg"
            };
        public static List<String> labels_extended =
            new List<String> {
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "cocacola",
                "cocacola",
                "cocacola",
                "cocacola",
                "cocacola",
                "cocacola",
                "cocacola",
                "cocacola",
                "cocacola",
                "cocacola",
                "fedex",
                "fedex",
                "fedex",
                "fedex",
                "fedex",
                "fedex",
                "fedex",
                "fedex",
                "fedex",
                "fedex",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo"
            };
        public static List<String> images_extended_2 =
            new List<String> {
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/46.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/47.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/48.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/49.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/50.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/51.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/52.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/53.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/54.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/55.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/56.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/57.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/58.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/59.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/60.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/61.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/62.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/63.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/64.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/65.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/66.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/67.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/68.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/69.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/70.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/71.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/72.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/73.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/74.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/75.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/76.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/77.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/78.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/79.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/80.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/81.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/82.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/83.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/84.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/85.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/86.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/87.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/88.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/89.jpg",
                "C:/Users/Onit/Documents/GitHub/logo-detector/test images/db_extended/90.jpg"
            };
        public static List<String> labels_extended_2 =
            new List<String> {
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "cocacola",
                "cocacola",
                "cocacola",
                "cocacola",
                "cocacola",
                "cocacola",
                "cocacola",
                "cocacola",
                "cocacola",
                "cocacola",
                "fedex",
                "fedex",
                "fedex",
                "fedex",
                "fedex",
                "fedex",
                "fedex",
                "fedex",
                "fedex",
                "fedex",
                "starbucks",
                "starbucks",
                "starbucks",
                "starbucks",
                "starbucks",
                "starbucks",
                "starbucks",
                "starbucks",
                "starbucks",
                "starbucks",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo",
                "tidak ditemukan logo"
            };
    }
}
